# Install script for directory: C:/Users/juan_/Documents/C++ Courses/C++/fltk-1.3.3/test

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/FLTK")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/adjuster.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/adjuster.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/adjuster.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/adjuster.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/arc.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/arc.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/arc.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/arc.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/ask.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/ask.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/ask.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/ask.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/bitmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/bitmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/bitmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/bitmap.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/blocks.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/blocks.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/blocks.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/blocks.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/boxtype.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/boxtype.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/boxtype.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/boxtype.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/browser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/button.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/button.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/button.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/button.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/buttons.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/checkers.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/checkers.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/checkers.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/checkers.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/clock.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/clock.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/clock.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/clock.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/colbrowser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/colbrowser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/colbrowser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/colbrowser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/color_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/color_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/color_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/color_chooser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/cursor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/cursor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/cursor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/cursor.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/curve.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/curve.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/curve.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/curve.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/demo.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/demo.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/demo.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/demo.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/device.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/device.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/device.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/device.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/doublebuffer.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/doublebuffer.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/doublebuffer.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/doublebuffer.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/editor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/editor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/editor.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/editor.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/fast_slow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/fast_slow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/fast_slow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/fast_slow.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/file_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/file_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/file_chooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/file_chooser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/fonts.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/fonts.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/fonts.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/fonts.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/forms.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/forms.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/forms.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/forms.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/hello.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/hello.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/hello.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/hello.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/help.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/help.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/help.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/help.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/icon.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/icon.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/icon.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/icon.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/iconize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/iconize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/iconize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/iconize.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/image.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/inactive.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/inactive.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/inactive.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/inactive.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/input.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/input.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/input.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/input.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/input_choice.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/input_choice.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/input_choice.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/input_choice.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/keyboard.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/keyboard.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/keyboard.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/keyboard.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/label.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/line_style.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/line_style.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/line_style.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/line_style.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/list_visuals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/list_visuals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/list_visuals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/list_visuals.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/mandelbrot.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/mandelbrot.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/mandelbrot.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/mandelbrot.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/menubar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/menubar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/menubar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/menubar.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/message.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/message.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/message.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/message.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/minimum.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/minimum.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/minimum.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/minimum.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/native-filechooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/native-filechooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/native-filechooser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/native-filechooser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/navigation.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/navigation.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/navigation.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/navigation.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/output.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/output.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/output.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/output.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/overlay.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/pack.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/pack.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/pack.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/pack.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/pixmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/pixmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/pixmap.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/pixmap.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/pixmap_browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/pixmap_browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/pixmap_browser.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/pixmap_browser.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/preferences.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/preferences.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/preferences.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/preferences.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/radio.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/radio.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/radio.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/radio.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/resize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/resize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/resize.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/resize.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/resizebox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/resizebox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/resizebox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/resizebox.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/rotated_text.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/rotated_text.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/rotated_text.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/rotated_text.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/scroll.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/scroll.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/scroll.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/scroll.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/subwindow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/subwindow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/subwindow.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/subwindow.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/sudoku.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/sudoku.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/sudoku.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/sudoku.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/symbols.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/symbols.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/symbols.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/symbols.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/tabs.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/tabs.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/tabs.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/tabs.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/table.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/threads.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/threads.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/threads.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/threads.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/tile.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/tile.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/tile.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/tile.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/tiled_image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/tiled_image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/tiled_image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/tiled_image.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/tree.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/tree.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/tree.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/tree.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/twowin.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/twowin.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/twowin.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/twowin.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/utf8.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/utf8.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/utf8.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/utf8.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/valuators.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/valuators.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/valuators.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/valuators.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/unittests.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/unittests.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/unittests.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/unittests.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/windowfocus.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/windowfocus.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/windowfocus.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/windowfocus.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/CubeView.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/CubeView.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/CubeView.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/CubeView.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/cube.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/cube.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/cube.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/cube.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/fractals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/fractals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/fractals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/fractals.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/fullscreen.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/fullscreen.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/fullscreen.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/fullscreen.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/glpuzzle.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/glpuzzle.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/glpuzzle.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/glpuzzle.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/gl_overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/gl_overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/gl_overlay.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/gl_overlay.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Debug/shape.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/Release/shape.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/MinSizeRel/shape.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin/fltk-examples" TYPE EXECUTABLE FILES "C:/Users/juan_/Documents/Binaries/fltk-1.3.3/bin/examples/RelWithDebInfo/shape.exe")
  endif()
endif()

