#
# FLTKConfig.cmake - FLTK CMake configuration file for external projects.
#
# This file is generated by CMake and used to load FLTK's settings for an external project.
# It defines the following variables
#  FLTK_INCLUDE_DIRS - FLTK include directories
#  FLTK_LIBRARIES    - list of FLTK libraries built
#  FLTK_FLUID_EXECUTABLE needed by fltk_wrap_ui()
#  FLTK_USE_FILE - sets things up to use FLTK

set(FLTK_VERSION 1.3.3)

include(${CMAKE_CURRENT_LIST_DIR}/FLTK-Targets.cmake)

set(FLTK_INCLUDE_DIRS "C:/Users/juan_/Documents/Binaries/fltk-1.3.3;C:/Users/juan_/Documents/C++ Courses/C++/fltk-1.3.3")
set(FLTK_USE_FILE ${CMAKE_CURRENT_LIST_DIR}/UseFLTK.cmake)
